apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-deployment
  labels:
    app: nlp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp-server
  template:
    metadata:
      labels:
        app: nlp-server
    spec:
      containers:
      - name: nlp-container
        image: lisxxxxxacr.azurecr.io/lis-nlp:xx
        ports:
        - containerPort: 8000