name: Docker Image CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: |
        docker build ./nlp -t ${{ secrets.ACR_LOGIN_SERVER }}/lis-nlp:${{ github.run_number }}
      
    - name: Login to the Container Registry  
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/lis-nlp:${{ github.run_number }}
