name: NLP model deployment CI/CD
on:
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      
    - name: Login with azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get key vault secrets
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secrets: 'ACR-LOGIN, ACR-USERNAME, ACR-PASSWORD, RG-NAME, AKS-NAME'
      id: acrsecrets

    - name: Login to the container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ steps.acrsecrets.outputs.ACR-LOGIN }}
        username: ${{ steps.acrsecrets.outputs.ACR-USERNAME }}
        password: ${{ steps.acrsecrets.outputs.ACR-PASSWORD }}
        
    - name: Build and push the docker image to container registry
      run: |
        docker build ./nlp/image -t ${{ steps.acrsecrets.outputs.ACR-LOGIN }}/lis-nlp:${{ github.run_number }}
        docker push ${{ steps.acrsecrets.outputs.ACR-LOGIN }}/lis-nlp:${{ github.run_number }}

    - name: Substitute image variable in nlp-deployment.yaml
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{github.workspace}}/nlp/nlp-deployment.yaml'
      env:
        spec.template.spec.containers.0.image: ${{ steps.acrsecrets.outputs.ACR-LOGIN }}/lis-nlp:${{ github.run_number }}

    - name: Display nlp-deployment.yaml content
      run: |
        cat ${{github.workspace}}/nlp/nlp-deployment.yaml

    - name: 'Deploy application and service to kubernetes cluster'
      run: |
        az aks get-credentials --resource-group ${{ steps.acrsecrets.outputs.RG-NAME }} --name ${{ steps.acrsecrets.outputs.AKS-NAME }}
        kubeclt apply -f ./nlp/nlp-deployment.yaml
        kubeclt apply -f ./nlp/nlp-service.yaml

        
        
    
