name: NLP model deployment CI/CD
on:
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      
    - name: Login with azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get key vault secrets
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secrets: 'ACR-LOGIN, ACR-USERNAME, ACR-PASSWORD, RG-NAME, APP-NAME'
      id: acrsecrets

    - name: Login to the container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ steps.acrsecrets.outputs.ACR-LOGIN }}
        username: ${{ steps.acrsecrets.outputs.ACR-USERNAME }}
        password: ${{ steps.acrsecrets.outputs.ACR-PASSWORD }}
        
    - name: Build and push the docker image to container registry
      run: |
        docker build ./nlp -t ${{ steps.acrsecrets.outputs.ACR-LOGIN }}/lis-nlp:${{ github.run_number }}
        docker push ${{ steps.acrsecrets.outputs.ACR-LOGIN }}/lis-nlp:${{ github.run_number }}

    - name: 'Deploy application container to the Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.acrsecrets.outputs.APP-NAME }}
        images: ${{ steps.acrsecrets.outputs.ACR-LOGIN }}/lis-nlp:${{ github.run_number }}
        
        
    
