name: Tensorflow Serving CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Download the ResNet SavedModel
      run: |
        mkdir /tmp/resnet
        curl -s http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz | \
        tar --strip-components=2 -C /tmp/resnet -xvz