name: Tensorflow Serving CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Download SavedModel
      run: |
        mkdir /tmp/nlpmodel
        curl -s http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz | \
        tar --strip-components=2 -C /tmp/nlpmodel -xvz

    - name: Commit image for deployment
      run: |
        docker run -d --name serving_base tensorflow/serving
        docker cp /tmp/nlpmodel serving_base:/models/nlpmodel
        docker commit --change "ENV MODEL_NAME nlpmodel" serving_base $USER/nlpmodel_serving
        docker kill serving_base
        docker rm serving_base
    
    - name: Login with azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get key vault secrets
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secrets: 'ACR-LOGIN, ACR-USERNAME, ACR-PASSWORD'
      id: acrsecrets

    - name: Login to the container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ steps.acrsecrets.outputs.ACR-LOGIN }}
        username: ${{ steps.acrsecrets.outputs.ACR-USERNAME }}
        password: ${{ steps.acrsecrets.outputs.ACR-PASSWORD }}

    - name: Upload the Docker image
      run: |
        docker tag $USER/nlpmodel_serving ${{ steps.acrsecrets.outputs.ACR-LOGIN }}/tensorflow-serving/nlp:${{ github.run_number }}
        docker push ${{ steps.acrsecrets.outputs.ACR-LOGIN }}/tensorflow-serving/nlp:${{ github.run_number }}
